/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeRouteImport } from './routes/home'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as RecordsRouteImport } from './routes/records'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as LearnIndexRouteImport } from './routes/learn.index'
import { Route as LearnThemeIdRouteImport } from './routes/learn.$themeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordsRoute = RecordsRouteImport.update({
  id: '/records',
  path: '/records',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnIndexRoute = LearnIndexRouteImport.update({
  id: '/learn/',
  path: '/learn/',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnThemeIdRoute = LearnThemeIdRouteImport.update({
  id: '/learn/$themeId',
  path: '/learn/$themeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/learn/$themeId': typeof LearnThemeIdRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/learn/$themeId': typeof LearnThemeIdRoute
  '/learn': typeof LearnIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/records': typeof RecordsRoute
  '/report': typeof ReportRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/survey': typeof SurveyRoute
  '/learn/$themeId': typeof LearnThemeIdRoute
  '/learn/': typeof LearnIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/records'
    | '/report'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/learn/$themeId'
    | '/learn/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/records'
    | '/report'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/learn/$themeId'
    | '/learn'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/profile'
    | '/records'
    | '/report'
    | '/settings'
    | '/signup'
    | '/survey'
    | '/learn/$themeId'
    | '/learn/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  RecordsRoute: typeof RecordsRoute
  ReportRoute: typeof ReportRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SurveyRoute: typeof SurveyRoute
  LearnThemeIdRoute: typeof LearnThemeIdRoute
  LearnIndexRoute: typeof LearnIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/records': {
      id: '/records'
      path: '/records'
      fullPath: '/records'
      preLoaderRoute: typeof RecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/': {
      id: '/learn/'
      path: '/learn'
      fullPath: '/learn/'
      preLoaderRoute: typeof LearnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn/$themeId': {
      id: '/learn/$themeId'
      path: '/learn/$themeId'
      fullPath: '/learn/$themeId'
      preLoaderRoute: typeof LearnThemeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  RecordsRoute: RecordsRoute,
  ReportRoute: ReportRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SurveyRoute: SurveyRoute,
  LearnThemeIdRoute: LearnThemeIdRoute,
  LearnIndexRoute: LearnIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
